services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./ollama/ollama:/root/.ollama
    networks:
      - app
    entrypoint: [ "/usr/bin/bash", "pull-mistral.sh" ]
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - ollama
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend
    environment:
      - OLLAMA_HOST=http://ollama:11434


networks:
  app:
    driver: bridge